nombre = 'cesar quintero'
print('uso del operador in:')
print('e' in nombre)
print('w' in nombre)
print()
print('uso de la funcion "len":')
print(len(nombre))
print()
print('uso del metodo "uper":')
print(nombre.upper())
print('uso del metodo "lower":')
print(nombre.lower())
print('uso del metodo "title":')
print(nombre.title())
print()
print('uso del metodo "count":')
print(nombre.count('e'))
print(nombre.count('Q'))
print(nombre.count('q'))
